version: 2

models:
  - name: powerpath_cyto_biopsy_silver
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [CASE_NO, TEST_NAME, SIGNED_OUT_DATE]
    columns:
      - name: SIGNED_OUT_DATE
        tests: [not_null]
      - name: TEST_NAME
        tests:
          - accepted_values:
              values: ['Breast Biopsy', 'Breast Large/Resection', 'Cytology GYN', 'Cytology NONGYN']